name: monarchium
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
  
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  country_state_city: ^0.1.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^0.22.0
  google_sign_in: ^5.0.7
  intl: any
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  firebase_dynamic_links: ^5.0.9
  firebase_storage: ^11.0.8
  url_launcher: ^6.1.7
  webview_flutter: ^4.0.0
  flutter_login_vk: ^2.2.2
  # mask_text_input_formatter: ^2.4.0
  libphonenumber: ^2.0.2
  mime_type: ^1.0.0
  cloud_firestore: ^4.3.0
  built_value: ^8.4.2
  built_collection: ^5.1.1
  # file_picker: ^4.6.1
  image_picker: ^0.8.6
  share_plus: ^4.5.3
  searchfield: ^0.7.2
  text_search: ^0.0.2
  proste_bezier_curve: ^2.0.2
  from_css_color: ^2.0.0
  sign_in_with_apple: ^4.3.0
  dropdown_search: ^5.0.5
  easy_debounce: ^2.0.3
  get_storage: ^2.0.3
  firebase_crashlytics: ^3.0.11
  flutter_launcher_icons: ^0.11.0
  dash_chat_2: ^0.0.15
  widgets_to_image: ^0.0.2
  path_provider: ^2.0.12
  device_preview: ^1.1.0
  purchases_flutter: ^4.9.1
  easy_image_viewer: ^1.2.0
  flutter_localizations: 
    sdk: flutter
  
dev_dependencies: 
  build_runner: ^2.3.3
  built_value_generator: ^8.4.2
  
  integration_test:
    sdk: flutter
    
  flutter_test: 
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poiret One
      fonts: 
        - asset: assets/fonts/PoiretOneRegular.ttf
          weight: 400
    - family: Cormorant
      fonts: 
        - asset: assets/fonts/CormorantRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/CormorantRomanRegular.ttf
          weight: 400
