// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcScTB7Qsxh8Hku20dDhB8dNR-CPKWGxE',
    appId: '1:484757252858:web:165fc3557ab1e412ae7743',
    messagingSenderId: '484757252858',
    projectId: 'monarchium-5f98b',
    authDomain: 'monarchium-5f98b.firebaseapp.com',
    storageBucket: 'monarchium-5f98b.appspot.com',
    measurementId: 'G-MW7PY2J5VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsLm9_6JzjeF_ZKenNgqUgwQknCV9RYoc',
    appId: '1:484757252858:android:dbe56495b4057fbfae7743',
    messagingSenderId: '484757252858',
    projectId: 'monarchium-5f98b',
    storageBucket: 'monarchium-5f98b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYRmRiqpxrXZ10IKzkY9xFYhLcUb_vfQE',
    appId: '1:484757252858:ios:2c2db5d76dbb5371ae7743',
    messagingSenderId: '484757252858',
    projectId: 'monarchium-5f98b',
    storageBucket: 'monarchium-5f98b.appspot.com',
    androidClientId: '484757252858-14dqt6vula4hknor6djtbnnqih393ujc.apps.googleusercontent.com',
    iosClientId: '484757252858-99atakj9kr1kp9gg5v2vq325cblv295f.apps.googleusercontent.com',
    iosBundleId: 'com.monarchium.app',
  );
}
